<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF5irg8h\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF5irg8h/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerF5irg8h.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerF5irg8h\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerF5irg8h\appProdProjectContainer(array(
    'container.build_hash' => 'F5irg8h',
    'container.build_id' => '7a689c8b',
    'container.build_time' => 1516274324,
));
