<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUixx9cn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUixx9cn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUixx9cn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUixx9cn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUixx9cn\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Uixx9cn',
    'container.build_id' => 'ba37f04d',
    'container.build_time' => 1516267981,
));
